version: '2'
networks:
  lb_web:
    external: true
  back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.${SUBNET}.0/24
services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST
    networks:
      - back
      - lb_web
  flectra:
    image: flectrahq/flectra:1.5
    links:
      - db
    volumes:
      - ./flectra:/var/lib/flectra
    networks:
      - back
  db:
    image: postgres:9.4
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - back
